import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body /* className={inter.className} */ >
        <div>
          <div className="navWrap">
            <nav className="navBar">
              <ul className="inlineGrid">
                <li>
                  <Link href="/"><img src="/m&p.png" width="70"></img></Link>
                </li>
                <li>
                  <Link href="/intro">회사소개</Link>
                  <ul>
                    <li><Link href="/intro">회사소개</Link></li>
                    <li><Link href="/intro/#history">연혁</Link></li>
                    <li><Link href="/intro/#address">오시는 길</Link></li>
                  </ul>
                </li>
                <li>
                  <Link href="/product">제품</Link>
                  <ul>
                    <li><Link href="/product/#car">자동차용 세라믹 부품</Link></li>
                    <li><Link href="/product/#semi">반도체 장비용 세라믹 부품</Link></li>
                    <li><Link href="/product/#industy">산업용 세라믹 부품</Link></li>
                  </ul>
                </li>
                <li>
                  <Link href="/business">사업</Link>
                  <ul>
                    <li><Link href="#">세라믹 부품 사업</Link></li>
                    <li><Link href="#">시험/고장분석/신뢰성 평가</Link></li>
                  </ul>
                </li>
                <li>
                  <Link href="/r&d">연구개발</Link>
                  <ul>
                    <li><Link href="#">세라믹 소재&부품 개발</Link></li>
                    <li><Link href="#">신뢰성 평가 기법 개발</Link></li>
                  </ul>
                </li>
              </ul>
            </nav>
          </div>
          <div className="subMenu"></div>
        </div>
        {children}
      </body>
    </html>
  );
}
